// <auto-generated />
using Exercicio2___FINAL.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exercicio2___FINAL.Migrations
{
    [DbContext(typeof(AlunosContext))]
    partial class AlunosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Exercicio2___FINAL.Models.Aluno", b =>
                {
                    b.Property<string>("AlunoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlunoID");

                    b.ToTable("Aluno");
                });

            modelBuilder.Entity("Exercicio2___FINAL.Models.Endereco", b =>
                {
                    b.Property<string>("EnderecoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlunoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEndereco")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnderecoID");

                    b.HasIndex("AlunoID");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Exercicio2___FINAL.Models.Endereco", b =>
                {
                    b.HasOne("Exercicio2___FINAL.Models.Aluno", null)
                        .WithMany("Endereco")
                        .HasForeignKey("AlunoID");
                });

            modelBuilder.Entity("Exercicio2___FINAL.Models.Aluno", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
